### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by rajadain** [TheAcademyofNaturalSciences/gwlf-e#10]
```
Traceback (most recent call last):
  File "single.py", line 56, in <module>
    result, _ = gwlfe.run(z)
  File "/Users/rajadain/.local/share/virtualenvs/drexeleds-sUBfOwqo/lib/python2.7/site-packages/gwlfe/gwlfe.py", line 121, in run
    StreamBank.CalculateStreamBankEros(z, Y)
  File "/Users/rajadain/.local/share/virtualenvs/drexeleds-sUBfOwqo/lib/python2.7/site-packages/gwlfe/StreamBank.py", line 142, in CalculateStreamBankEros
    z.TileDrainN[Y][i] + \
  File "/Users/rajadain/.local/share/virtualenvs/drexeleds-sUBfOwqo/lib/python2.7/site-packages/gwlfe/Memoization.py", line 46, in __call__
    ret = self.result = self.f(*args)
  File "/Users/rajadain/.local/share/virtualenvs/drexeleds-sUBfOwqo/lib/python2.7/site-packages/gwlfe/Output/Loading/StreamBankN_1.py", line 103, in StreamBankN_1_f
    AvSlope, SedAAdjust, StreamLength, n42b, UrbBankStab, SedNitr, BankNFrac, n69c)
  File "/Users/rajadain/.local/share/virtualenvs/drexeleds-sUBfOwqo/lib/python2.7/site-packages/gwlfe/BMPs/Stream/NURBBANK.py", line 41, in NURBBANK_f
    AvSlope, SedAAdjust, StreamLength, SedNitr, BankNFrac) * n69c
ZeroDivisionError: float division by zero
```

Seen on these input files:

[huc12__60099.json.txt](https://github.com/drexeleds/gwlf-e/files/2238978/huc12__60099.json.txt)
[huc12__60100.json.txt](https://github.com/drexeleds/gwlf-e/files/2238979/huc12__60100.json.txt)
[huc12__60101.json.txt](https://github.com/drexeleds/gwlf-e/files/2238980/huc12__60101.json.txt)

Using this test file: https://github.com/rajadain/mmw-gwlfe-comparison/blob/master/drexeleds/single.py which runs one input JSON at a time.

**Comment by gnitsua** [comment]
This is absolutely a mistake, I will correct it
